name: iiit_sonepat_stable
description: College App made by students of IIIT Sonepat for the students of IIIT Sonepat

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  native_pdf_view: any
  fluttertoast: ^8.0.7
  percent_indicator: "^2.1.7+2"
  backdrop: ^0.6.0
  cloud_firestore: ^1.0.6
  flutter_svg: ^0.22.0
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/mann.jpg
    - assets/images/doja.jpg
    - assets/images/diddi.jpg
    - assets/images/rajiv.jpg
    - assets/images/class.png
    - assets/homepageImages/
    - assets/subjectPageImages/
    - assets/subjectPageImages/maths.png
    - assets/subjectPageImages/web_design.webp
    - assets/subjectPageImages/
    - assets/iiit_sonepat_syllabus.pdf
    - assets/images/IIIT Sonepat Logo.png

  fonts:
    - family: MonoLisa
      fonts:
        - asset: fonts/MonoLisa-Regular.ttf
    - family: Questrial
      fonts:
        - asset: fonts/Questrial-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Medium.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Schyler
      fonts:
        - asset: fonts/Comfortaa-VariableFont_wght.ttf